### ISSUE TITLE
Think about different way of sharing data between frontend and backend

### ISSUE THREAD

**Issue by fischeversenker** [fischeversenker/intellisnake#19]
The matrix conversion in the frontend (canvas to matrix) is the most costly part currently. As fas as I understood its the same for the backend where we need to basically do the same process in reverse, going from the matrix to an image.
Is there a better way to send data to the backend?

To help with solving this I need to understand how the backend expects the data and what it actually needs, @azacha .

**Comment by fischeversenker** [comment]
Generation Message from FE to BE:
```
{
  messageId: 0,
  type: 'generation',
  data: {
    snakes: [{
      id: 0,
      color: [0, 4, 255],
    }, {
      id: 1,
      color: [...],
    }, {
      id: 2,
      color: [],
    }],
  },
}
```
Data Message from FE to BE:
```
{
  messageId: 1,
  type: 'data',
  data: {
    matrix: [[0, 0, 0], [0, 4, 255], ...],
    snakeIds: [666, 677, 688],
  }
}
```

**Comment by fischeversenker** [comment]
Other requirements for this to work:
- food has always the same color.
- food has a color that no snake has.

**Comment by azacha** [comment]
Communication
FE:start
BE:start
FE:data
BE:data
....
BE:generation
FE:generation (reward)
BE:start
FE:data

**Comment by fischeversenker** [comment]
I'd say we rocked this 🚀 
Closing this now with an A+ to ourselves :+1:
