### ISSUE TITLE
Matter.js might be broken: Snakes pass through boundaries

### ISSUE THREAD

**Issue by azacha** [fischeversenker/intellisnake#25]
This is an unresolved issue since February 2014 in matter.js. Continous Collsision Dedection branch has been abadonded.

https://github.com/liabru/matter-js/issues/5

**Comment by fischeversenker** [comment]
I'm pretty sure the problem has nothing to do with CCD... there are plenty of working examples in their documentation (even though the chains seem to be broken on your machine :eyes:). I still believe this is something I misconfigured... I'll give it a few more tries to fix this.
If nothing helps I'll have a look at other physics engines :+1:

**Comment by fischeversenker** [comment]
The problem was not due to matter's CCD issues. I'll close this issue for now 👌
