### ISSUE TITLE
I want to be able to save and restore the AI model

### ISSUE THREAD

**Issue by fischeversenker** [fischeversenker/intellisnake#27]
2 buttons in Info Overlay:
- "Start": starts the game/evolution/simulation with generation 0
- "Resume": resume with the last saved generation

Resume: 
MessageType "resume"
```
data: { snakes: [
  {
    id: 666
    color: [0, 100, 200],
  }, {
    id: 678,
    ....
  }
] }
```

**Comment by azacha** [comment]
How do we want go choose the model? Just load the one with the highest generation?

Why not stick to the working communication via MessageType.

**Comment by fischeversenker** [comment]
looks like it's working :+1:
closing this...
